package com.data_management;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.stream.Stream;

/**
 * Reads patient data from output files generated by HealthDataSimulator
 * using the --output file:<directory> argument.
 * Each line follows the format:
 * "Patient ID: X, Timestamp: Y, Label: Z, Data: W"
 */
public class FileDataReader implements DataReader {

    private String directory;

    /**
     * Constructs a FileDataReader that reads from the specified directory.
     *
     * @param directory the path to the directory containing output files
     */
    public FileDataReader(String directory) {
        this.directory = directory;
    }

    /**
     * Reads all .txt files in the directory and stores the parsed data
     * into the provided DataStorage instance.
     *
     * @param dataStorage the storage where parsed data will be stored
     * @throws IOException if the directory cannot be read or a file cannot be opened
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        Path dirPath = Paths.get(directory);

        try (Stream<Path> files = Files.walk(dirPath)) {
            files.filter(p -> p.toString().endsWith(".txt"))
                    .forEach(p -> {
                        try {
                            parseFile(p, dataStorage);
                        } catch (IOException e) {
                            System.err.println("Error reading file: " + p + " - " + e.getMessage());
                        }
                    });
        }
    }

    /**
     * Parses a single file and adds each record to DataStorage.
     *
     * @param filePath the path to the file
     * @param dataStorage the storage to add records to
     * @throws IOException if the file cannot be read
     */
    private void parseFile(Path filePath, DataStorage dataStorage) throws IOException {
        try (BufferedReader reader = new BufferedReader(new FileReader(filePath.toFile()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                parseLine(line, dataStorage);
            }
        }
    }

    /**
     * Parses a single line and adds the record to DataStorage.
     * Expected format: "Patient ID: X, Timestamp: Y, Label: Z, Data: W"
     *
     * @param line the line to parse
     * @param dataStorage the storage to add the record to
     */
    private void parseLine(String line, DataStorage dataStorage) {
        try {
            String[] parts = line.split(", ");

            int patientId = Integer.parseInt(parts[0].replace("Patient ID: ", "").trim());
            long timestamp = Long.parseLong(parts[1].replace("Timestamp: ", "").trim());
            String label = parts[2].replace("Label: ", "").trim();
            double data = Double.parseDouble(parts[3].replace("Data: ", "").trim());

            dataStorage.addPatientData(patientId, data, label, timestamp);

        } catch (Exception e) {
            System.err.println("Skipping malformed line: " + line);
        }
    }
}